[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["homework9_IoC_plus_communication_broker"]
	#"homework1_unittests","homework2_mocking","homework3_command"
