[package]
name = "serde_bson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.159",features =["derive"]}
serde_json = "1.0.96"
serde_with = "2.3.2"
