[package]
name = "test_wasi_embed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
wasmtime = "6.0.0"
#wasmtime-wasi = {version = "6.0.0", optional=true}
wasmtime-wasi = "6.0.0"
