[package]
name = "game-mechanics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib_game_mech"
path = "./src/lib.rs"

[dependencies]
mockall = "0.11.4"
rstest = "0.17.0"
