name: Example workflow

on:
  push:
    branches:
      - main
    
env:
  SOME_VAR: ok

jobs:
  test-simple-tasks:
    runs-on: ubuntu-latest
    env:
      task_variable: "alex variable"
    steps:
      - uses: actions/checkout@v3
      - name: Get author name
        id: author
        run: echo "author=$(git show -s --format=%an)" >> $GITHUB_OUTPUT
          #        run: echo "{name}={value} >>GITHUB_OUTPUT::$(git show -s --format=%an)"
          #run: echo "::set-output name=author::$(git show -s --format=%an)"
      - name: Print author name
        run: echo "${{ steps.author.outputs.author }}"
      - name: Print author name with an environment variable
        run: echo $AUTHOR_NAME
        env:
          AUTHOR_NAME: ${{ steps.author.outputs.author }}
      - name: Log levels
        run: |
          #       echo "::debug::This is a debug message"
          echo "::notice::This is an info message"
          echo "::notice::Printin env variable: ${{ env.task_variable }}"
          echo "::warning::This is a warning"
          echo "::error::This is an error"    
      - name: Print variable
        run: |
          echo "This is your variable $SOME_VAR"
  ubuntu_2204_task:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - name: Build
        run: dotnet build
      - name: Run tests
        run: dotnet test 
  windows_runner:
    runs-on: windows-latest
    env:
      win_var1: "windows_variables"
    steps:
    - shell: cmd
      run: |
        @chcp 65001>nul
        echo foo=bar >> $GITHUB_OUTPUT
        echo "hello!" 
        echo "tasl variable ${{ env.win_var1 }}" 
        echo "global variable ${{ env.SOME_VAR }} "

